### ISSUE TITLE
Aula 5 - Exercício de Inclusão de dados

### ISSUE THREAD

**Issue by Albervan** [Albervan/nlw2020#1]
```
$ node src/database/teste.js
(node:15996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'run' of undefined
    at module.exports (D:\Repositorios\PARTICULAR\GitHub\Rocketseat\nlw2020\src\database\createProffy.js:4:37)
    at D:\Repositorios\PARTICULAR\GitHub\Rocketseat\nlw2020\src\database\teste.js:35:11
(node:15996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:15996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Exemplo do Mayk (1:14:25)**
![Anotação 2020-08-10 032304](https://user-images.githubusercontent.com/54541416/89759738-da540b00-dab8-11ea-9a09-16177a380866.jpg)

**Comment by Albervan** [comment]
- [x] Definição do array classSchedule em 56:43;
- [x] Revisto as implementações até 48:40 do video;
